(in-package :sm-dsl)

(defun trace-all-rules ()
  (trace rmSpaces)
  (trace statemachine0)
  (trace machine)
  (trace machineName)
  (trace optional-initially)
  (trace returnEmptyStatementsBag)
  (trace states)
  (trace state)
  (trace stateName)
  (trace events)
  (trace eventName)
  (trace statements)
  (trace sendStatement)
  (trace callStatement)
  (trace expr)
  (trace dollarExpr)
  (trace rawExpr)
  (trace callExpr)
  (trace optionalParameters)
  (trace returnEmptyExprsBag)
  (trace parameters)
  (trace pipeline)
  (trace morePipes))
